name: Backend

env:
  server: webh04.biohost.net
  # port:
  # protocol:
  username: m3967ftp-b
  remote-root: /home/m3967/Sites/backend/

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

concurrency: backend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # https://github.com/SamKirkland/FTP-Deploy-Action
      - name: Deploy project (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ env.server }}
          # port: ${{ env.port }}
          # protocol: ${{ env.protocol }}
          server-dir: ${{ env.remote-root }}
          username: ${{ env.username }}
          local-dir: backend/dist/
          password: ${{ secrets.BACKEND_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            /.well-known
            /.well-known/**
            /.user.ini
            /php.ini
            /prepend.inc.php
            /.htaccess
            /site/config.php
            /site/assets/backups/**
            /site/assets/cache/**
            /site/assets/files/**
            /site/assets/logs/**
            /site/assets/sessions/**
            /site/modules/.htaccess

      # https://github.com/easingthemes/ssh-deploy
      # - name: Deploy project (SSH)
      #   uses: easingthemes/ssh-deploy@v5.1.0
      #   with:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: "-avzr --delete"
      #     SOURCE: "backend/dist/"
      #     REMOTE_HOST: ${{ env.server }}
      #     # REMOTE_PORT: ${{ env.port }}
      #     REMOTE_USER: ${{ env.username }}
      #     # TARGET: ${{ env.remote-root }}
      #     EXCLUDE: "/.user.ini, /.well-known, /php.ini, /prepend.inc.php, /.htaccess, /site/config.php, /site/assets/backups, /site/assets/cache, /site/assets/files, /site/assets/logs, /site/assets/sessions, /site/modules/.htaccess"
